diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=DonaLdZY
user.email=760463769@qq.com
http.sslverify=false
http.postbuffer=524288000
gui.recentrepo=C:/Users/DonaLdZY/Documents/Code-Projects/chess
safe.directory=*
safe.directory=*
credential.https://gitee.com.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/joenghl/2023AI.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.github.url=git@github.com:DonaLdZY/2023AI.git
remote.github.fetch=+refs/heads/*:refs/remotes/github/*
